### ISSUE TITLE
visible password history

### ISSUE THREAD

**Issue by leklachu** [peanutbutterandcrackers/chiyoko#1]
Bash history saves your typed commands, so typing your root-capable password as an argument in bash, probably not such a good idea.

It comes in your suggestions near the end of the README, on how to shutdown after running.

$ python3 chiyoko.py SOURCE DESTINATION -I -V && sudo -S poweroff <<< "YOURPASSWORDGOESHERE"

'shutdown' might have a way to run a process and shut down after? Or you could suggest running the whole command as sudo, and having it run your image script as the correct user. There's probably a better way; I don't know.

**Comment by peanutbutterandcrackers** [comment]
I have fixed that now... removed the tip altogether. lol 

Thank you for the report :+1:
